---
- name: Set nginx rc.conf flags
  sysrc: name={{ item.name }} value={{ item.value }} state=present
  with_items:
    - { name: nginx_enable, value: "YES" }

- name: upload nginx config
  template: src=nginx.conf.j2 dest="/usr/local/etc/nginx/nginx.conf" owner="root" group="wheel" mode=0644
  notify: restart nginx

- name: Enable nginx
  service: name="nginx" state="running" enabled="yes"
