---

- name: Create directory structure for service {{ svscan_service_name }}
  file: path="{{ item }}" state=directory mode=0755
  with_items:
  - "{{svscan_src}}/{{ svscan_service_name }}/log/main"
  - "{{svscan_src}}/{{ svscan_service_name }}/env"

- name: Create log directory for service {{ svscan_service_name }}
  file: path="{{ item }}" state=directory mode=0755 owner=nobody group=nobody
  with_items:
  - "{{svscan_src}}/{{ svscan_service_name }}/log/main"

- name: Copy the log script
  copy: src=logger_script dest={{svscan_src}}/{{ svscan_service_name }}/log/run owner="root" group="wheel" mode=0755
