- name: Create empty list of packages for the sets
  template:  src=pkglist.j2 dest="/usr/local/etc/poudriere.d/{{item.name}}-{{item.default_ports}}-{{item.default_set}}-pkglist" owner=root group=wheel mode=0644
  with_items: "{{poudriere_jail_list}}"


- name: Create empty make.conf files for the sets
  template:  src=make.conf.j2 dest="/usr/local/etc/poudriere.d/{{item.name}}-{{item.default_ports}}-{{item.default_set}}-make.conf" owner=root group=wheel mode=0644
  with_items: "{{poudriere_jail_list}}"

- name: upload makefile
  copy: src=files/make.sh dest={{svscan_src}}/poudriere/make.sh owner=root group=wheel mode=0755
