---
- name: create queue dir
  file: dest={{svscan_src}}/poudriere/queue/ state=directory owner=root group=wheel mode=0755

- name: Copy the supervisor script
  template: src=svscan_script.j2 dest="{{svscan_src}}/poudriere/run" owner="root" group="wheel" mode=0755
  notify: restart poudriere

- name: activate poudriere queue service
  svc: name=poudriere state=started  enabled=yes service_dir="{{svscan_dir}}" service_src="../..{{svscan_src}}"

